[package]
name = "income_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.33.2", features = ["csv"] }
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
